// <auto-generated />
using System;
using FishingBuddy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FishingBuddy.Data.Migrations
{
    [DbContext(typeof(FishingBuddyDbContext))]
    [Migration("20260607171434_ReplaceJmbgWithAddressInAppUser")]
    partial class ReplaceJmbgWithAddressInAppUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("FishFishingSpot", b =>
                {
                    b.Property<int>("MostLikelyCatchFishID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PossibleSpotsSpotID")
                        .HasColumnType("INTEGER");

                    b.HasKey("MostLikelyCatchFishID", "PossibleSpotsSpotID");

                    b.HasIndex("PossibleSpotsSpotID");

                    b.ToTable("FishingSpotFish", (string)null);
                });

            modelBuilder.Entity("FishUser", b =>
                {
                    b.Property<int>("FavoriteFishFishID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FavoritedByUsersUserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("FavoriteFishFishID", "FavoritedByUsersUserID");

                    b.HasIndex("FavoritedByUsersUserID");

                    b.ToTable("UserFavoriteFish", (string)null);
                });

            modelBuilder.Entity("FishingBuddy.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("OIB")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("FishingBuddy.Models.Attachment", b =>
                {
                    b.Property<int>("AttachmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatchRecordID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("AttachmentID");

                    b.HasIndex("CatchRecordID");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("FishingBuddy.Models.Bait", b =>
                {
                    b.Property<int>("BaitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AveragePriceEur")
                        .HasColumnType("TEXT");

                    b.Property<string>("BaitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("BaitType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreparationMethod")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("BaitID");

                    b.ToTable("Baits");
                });

            modelBuilder.Entity("FishingBuddy.Models.CatchRecord", b =>
                {
                    b.Property<int>("CatchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CatchDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FishID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LengthCm")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("CatchID");

                    b.HasIndex("FishID");

                    b.HasIndex("UserID");

                    b.ToTable("CatchRecords");
                });

            modelBuilder.Entity("FishingBuddy.Models.Fish", b =>
                {
                    b.Property<int>("FishID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CatchSeason")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FavouriteBaitID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FleshColor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreferredMethodID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SpeciesName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("FishID");

                    b.HasIndex("FavouriteBaitID");

                    b.HasIndex("PreferredMethodID");

                    b.ToTable("Fish");
                });

            modelBuilder.Entity("FishingBuddy.Models.FishingLicense", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("FishingLicenses");
                });

            modelBuilder.Entity("FishingBuddy.Models.FishingSpot", b =>
                {
                    b.Property<int>("SpotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BoatAccess")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPiers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpotName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("SpotID");

                    b.ToTable("FishingSpots");
                });

            modelBuilder.Entity("FishingBuddy.Models.Technique", b =>
                {
                    b.Property<int>("TechniqueID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PerformanceNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TechniqueName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("TutorialUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("TechniqueID");

                    b.ToTable("Techniques");
                });

            modelBuilder.Entity("FishingBuddy.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FishFishingSpot", b =>
                {
                    b.HasOne("FishingBuddy.Models.Fish", null)
                        .WithMany()
                        .HasForeignKey("MostLikelyCatchFishID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FishingBuddy.Models.FishingSpot", null)
                        .WithMany()
                        .HasForeignKey("PossibleSpotsSpotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FishUser", b =>
                {
                    b.HasOne("FishingBuddy.Models.Fish", null)
                        .WithMany()
                        .HasForeignKey("FavoriteFishFishID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FishingBuddy.Models.User", null)
                        .WithMany()
                        .HasForeignKey("FavoritedByUsersUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FishingBuddy.Models.Attachment", b =>
                {
                    b.HasOne("FishingBuddy.Models.CatchRecord", "CatchRecord")
                        .WithMany("Attachments")
                        .HasForeignKey("CatchRecordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CatchRecord");
                });

            modelBuilder.Entity("FishingBuddy.Models.CatchRecord", b =>
                {
                    b.HasOne("FishingBuddy.Models.Fish", "Fish")
                        .WithMany("CatchRecords")
                        .HasForeignKey("FishID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FishingBuddy.Models.User", "User")
                        .WithMany("CatchRecords")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fish");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FishingBuddy.Models.Fish", b =>
                {
                    b.HasOne("FishingBuddy.Models.Bait", "FavouriteBait")
                        .WithMany("PreferredByFish")
                        .HasForeignKey("FavouriteBaitID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FishingBuddy.Models.Technique", "PreferredMethod")
                        .WithMany("FishUsingTechnique")
                        .HasForeignKey("PreferredMethodID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FishingBuddy.Models.Equipment", "Equipment", b1 =>
                        {
                            b1.Property<int>("FishID")
                                .HasColumnType("INTEGER");

                            b1.HasKey("FishID");

                            b1.ToTable("Fish");

                            b1.WithOwner()
                                .HasForeignKey("FishID");

                            b1.OwnsOne("FishingBuddy.Models.FLine", "FLine", b2 =>
                                {
                                    b2.Property<int>("EquipmentFishID")
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("ThicknessMm")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Type")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("EquipmentFishID");

                                    b2.ToTable("Fish");

                                    b2.WithOwner()
                                        .HasForeignKey("EquipmentFishID");
                                });

                            b1.OwnsOne("FishingBuddy.Models.FReel", "FReel", b2 =>
                                {
                                    b2.Property<int>("EquipmentFishID")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Size")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Type")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("EquipmentFishID");

                                    b2.ToTable("Fish");

                                    b2.WithOwner()
                                        .HasForeignKey("EquipmentFishID");
                                });

                            b1.OwnsOne("FishingBuddy.Models.FRod", "FRod", b2 =>
                                {
                                    b2.Property<int>("EquipmentFishID")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("Action")
                                        .HasColumnType("INTEGER");

                                    b2.Property<decimal>("LengthMeters")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("MaxWeightRatingGrams")
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("MinWeightRatingGrams")
                                        .HasColumnType("INTEGER");

                                    b2.HasKey("EquipmentFishID");

                                    b2.ToTable("Fish");

                                    b2.WithOwner()
                                        .HasForeignKey("EquipmentFishID");
                                });

                            b1.Navigation("FLine")
                                .IsRequired();

                            b1.Navigation("FReel")
                                .IsRequired();

                            b1.Navigation("FRod")
                                .IsRequired();
                        });

                    b.Navigation("Equipment")
                        .IsRequired();

                    b.Navigation("FavouriteBait");

                    b.Navigation("PreferredMethod");
                });

            modelBuilder.Entity("FishingBuddy.Models.FishingLicense", b =>
                {
                    b.HasOne("FishingBuddy.Models.User", "User")
                        .WithOne("FishingLicense")
                        .HasForeignKey("FishingBuddy.Models.FishingLicense", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FishingBuddy.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FishingBuddy.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FishingBuddy.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FishingBuddy.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FishingBuddy.Models.Bait", b =>
                {
                    b.Navigation("PreferredByFish");
                });

            modelBuilder.Entity("FishingBuddy.Models.CatchRecord", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("FishingBuddy.Models.Fish", b =>
                {
                    b.Navigation("CatchRecords");
                });

            modelBuilder.Entity("FishingBuddy.Models.Technique", b =>
                {
                    b.Navigation("FishUsingTechnique");
                });

            modelBuilder.Entity("FishingBuddy.Models.User", b =>
                {
                    b.Navigation("CatchRecords");

                    b.Navigation("FishingLicense");
                });
#pragma warning restore 612, 618
        }
    }
}
